Repository SOPT-all/36-COLLABORATION-ANDROID-MCDONALDS, pull requests merged in 2025-05, with the labels that each got.

#6 [ADD/#5] Designsystem 및 drawable 리소스 추가
  app/src/main/java/org/sopt/mcdonalds/core/designsystem/theme/Color.kt
  app/src/main/java/org/sopt/mcdonalds/core/designsystem/theme/Theme.kt
  app/src/main/java/org/sopt/mcdonalds/core/designsystem/theme/Type.kt
  app/src/main/res/drawable/ic_back_24.xml
  app/src/main/res/drawable/ic_close_24.xml
  app/src/main/res/drawable/ic_delete_28.xml
  app/src/main/res/drawable/ic_down_chevron_20.xml
  app/src/main/res/drawable/ic_edit_28.xml
  app/src/main/res/drawable/ic_hamburger.xml
  app/src/main/res/drawable/ic_left_chevron_24.xml
  app/src/main/res/drawable/ic_map_location_64.xml
  app/src/main/res/drawable/ic_mcdonalds_location.xml
  app/src/main/res/drawable/ic_menu_20.xml
  app/src/main/res/drawable/ic_minus_24.xml
  app/src/main/res/drawable/ic_plus_24.xml
  app/src/main/res/drawable/ic_search_24.xml
  app/src/main/res/drawable/ic_up_chevron_20.xml
  app/src/main/res/drawable/ic_warning_20.xml
  app/src/main/res/drawable/img_drink_coke.png
  app/src/main/res/drawable/img_drink_fanta.png
  app/src/main/res/drawable/img_drink_mango_icetea.png
  app/src/main/res/drawable/img_drink_peach_icetea.png
  app/src/main/res/drawable/img_drink_sprite.png
  app/src/main/res/drawable/img_drink_sprite_large.png
  app/src/main/res/drawable/img_drink_zero_coke.png
  app/src/main/res/drawable/img_map.png
  app/src/main/res/drawable/img_side_coleslaw.png
  app/src/main/res/drawable/img_side_fries.png
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
Labels: 💄 Design

#9 [ADD/#7] Github label 세팅
  .github/labels.json
Labels: ⚙ Setting

#13 [UI/#8] 공통 컴포넌트 구현
  app/src/main/java/org/sopt/mcdonalds/core/designsystem/component/.gitkeep
  app/src/main/java/org/sopt/mcdonalds/core/designsystem/component/ChipButton.kt
  app/src/main/java/org/sopt/mcdonalds/core/designsystem/component/DefaultTopBar.kt
  app/src/main/java/org/sopt/mcdonalds/core/designsystem/component/NumberIncrementer.kt
Labels: 💄 Design, 😎 종명

#19 [UI/#18] 주문내역 페이지 리스트 컴포넌트 구현
  app/src/main/java/org/sopt/mcdonalds/presentation/history/component/HistoryCartItem.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/history/component/HistoryRecentBurgerItem.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/history/component/HistoryResultBar.kt
  app/src/main/res/values/strings.xml
Labels: 💄 Design, 😍 성하

#21 [UI/#14] 매장찾기 화면 구현
  app/src/main/java/org/sopt/mcdonalds/core/designsystem/component/ChipButton.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/store/StoreScreen.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/store/component/StoreFilterGroup.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/store/component/StoreInformationCard.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/store/component/StoreLocationFab.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/store/component/StoreTopBar.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/store/type/StoreType.kt
  app/src/main/res/drawable/ic_my_location.xml
  app/src/main/res/drawable/ic_right_chevron.xml
  app/src/main/res/values/strings.xml
Labels: 💄 Design, 😎 종명

#22 [UI/#15] 메뉴 리스트 화면 구현
  app/src/main/java/org/sopt/mcdonalds/core/designsystem/component/ChipButton.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/menu/MenuListScreen.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/menu/component/MenuListContent.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/menu/component/MenuListFilterGroup.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/menu/component/MenuListTopBar.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/menu/model/Menu.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/menu/type/MenuType.kt
  app/src/main/res/values/strings.xml
Labels: 💄 Design, 😎 종명

#23 [UI/#17] 상세 주문 컴포넌트 구현
  app/src/main/java/org/sopt/mcdonalds/presentation/order/component/OrderBurgerDetailContainer.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/component/OrderButton.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/component/OrderIngredientChangeContainer.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/component/OrderSetSelectButton.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/component/OrderSideChangeContainer.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/component/OrderSideDetailContainer.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/model/Ingredient.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/model/Side.kt
  app/src/main/res/drawable/img_burger_set.png
  app/src/main/res/drawable/img_burger_single.png
  app/src/main/res/values/strings.xml
Labels: 💄 Design, 🤩 형석

#30 [UI/#24] 상세 주문 뷰 구현
  app/src/main/java/org/sopt/mcdonalds/presentation/order/OrderScreen.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/component/OrderButton.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/component/OrderIngredientChangeContainer.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/component/OrderSetSelectButton.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/model/Burger.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/navigation/.gitkeep
  app/src/main/java/org/sopt/mcdonalds/presentation/order/type/OrderType.kt
  app/src/main/res/values/strings.xml
Labels: 💄 Design, 🤩 형석

#31 [FEAT/#25] 상점 화면 로직..은 없고 네비게이션
  app/src/main/java/org/sopt/mcdonalds/core/designsystem/component/ChipButton.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/main/MainActivity.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/main/MainScreen.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/main/component/.gitkeep
  app/src/main/java/org/sopt/mcdonalds/presentation/main/navigation/.gitkeep
  app/src/main/java/org/sopt/mcdonalds/presentation/menu/component/MenuListFilterGroup.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/store/StoreScreen.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/store/component/StoreFilterGroup.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/store/component/StoreInformationCard.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/store/navigation/StoreNavigation.kt
Labels: ✨ Feature, 😎 종명

#27 [UI/#20] 주문내역 뷰 구현
  app/src/main/java/org/sopt/mcdonalds/presentation/history/HistoryScreen.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/history/component/HistoryCartItem.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/history/component/HistoryRecentBurgerItem.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/history/component/HistoryResultBar.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/history/model/Cart.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/history/model/RecentBurger.kt
  app/src/main/res/values/strings.xml
Labels: 💄 Design, 😍 성하

#33 [FEAT/#26] 메뉴리스트 화면 로직 구현
  app/src/main/java/org/sopt/mcdonalds/presentation/.gitkeep
  app/src/main/java/org/sopt/mcdonalds/presentation/main/MainActivity.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/main/MainScreen.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/menu/MenuListScreen.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/menu/MenuListViewModel.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/menu/component/MenuListContent.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/menu/component/MenuListFilterGroup.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/menu/navigation/MenuListNavigation.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/menu/state/MenuListContract.kt
Labels: ✨ Feature, 😎 종명

#35 [FEAT/#34] 메뉴리스트 화면 API 연결
  app/src/main/java/org/sopt/mcdonalds/core/network/AuthInterceptor.kt
  app/src/main/java/org/sopt/mcdonalds/core/network/BaseResponse.kt
  app/src/main/java/org/sopt/mcdonalds/core/network/di/NetworkModule.kt
  app/src/main/java/org/sopt/mcdonalds/data/.gitkeep
  app/src/main/java/org/sopt/mcdonalds/data/menu/datasource/MenuDataSource.kt
  app/src/main/java/org/sopt/mcdonalds/data/menu/di/RepositoryModule.kt
  app/src/main/java/org/sopt/mcdonalds/data/menu/di/ServiceModule.kt
  app/src/main/java/org/sopt/mcdonalds/data/menu/dto/MenuDetailResponse.kt
  app/src/main/java/org/sopt/mcdonalds/data/menu/dto/MenuListResponse.kt
  app/src/main/java/org/sopt/mcdonalds/data/menu/mapper/MenuMapper.kt
  app/src/main/java/org/sopt/mcdonalds/data/menu/repository/MenuRepositoryImpl.kt
  app/src/main/java/org/sopt/mcdonalds/data/menu/service/MenuService.kt
  app/src/main/java/org/sopt/mcdonalds/domain/.gitkeep
  app/src/main/java/org/sopt/mcdonalds/domain/menu/model/Menu.kt
  app/src/main/java/org/sopt/mcdonalds/domain/menu/model/MenuDetail.kt
  app/src/main/java/org/sopt/mcdonalds/domain/menu/repository/MenuRepository.kt
  app/src/main/java/org/sopt/mcdonalds/domain/menu/usecase/GetMenuDetailUseCase.kt
  app/src/main/java/org/sopt/mcdonalds/domain/menu/usecase/GetMenusUseCase.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/menu/MenuListScreen.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/menu/MenuListViewModel.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/menu/component/MenuListContent.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/menu/model/Menu.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/menu/state/MenuListContract.kt
Labels: ✨ Feature, 📬 API, 😎 종명

#36 [FEAT/#32] 상세 주문 화면 로직 구현
  app/src/main/java/org/sopt/mcdonalds/presentation/main/MainScreen.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/OrderScreen.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/OrderViewModel.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/navigation/.gitkeep
  app/src/main/java/org/sopt/mcdonalds/presentation/order/navigation/OrderNavigation.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/state/OrderContract.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/type/SetType.kt
Labels: ✨ Feature, 🤩 형석

#40 [HOFIX/#24] uiState 캡슐화 및 뷰에서 수집
  app/src/main/java/org/sopt/mcdonalds/presentation/order/OrderScreen.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/OrderViewModel.kt
Labels: 🐛 Fix, 🤩 형석

#41 [UI/#28] 주문내역 변경 BottomSheet 구현
  app/src/main/java/org/sopt/mcdonalds/presentation/bottomsheet/CartEditBottomSheetScreen.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/history/HistoryScreen.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feature, 💄 Design, 😍 성하

#44 [FEAT/#38] 카트 담기 api 연결
  app/src/main/java/org/sopt/mcdonalds/core/network/BaseResponseWithNull.kt
  app/src/main/java/org/sopt/mcdonalds/data/cart/datasource/CartDataSource.kt
  app/src/main/java/org/sopt/mcdonalds/data/cart/di/RepositoryModule.kt
  app/src/main/java/org/sopt/mcdonalds/data/cart/di/ServiceModule.kt
  app/src/main/java/org/sopt/mcdonalds/data/cart/dto/CartPostRequest.kt
  app/src/main/java/org/sopt/mcdonalds/data/cart/mapper/CartMapper.kt
  app/src/main/java/org/sopt/mcdonalds/data/cart/repository/CartRepositoryImpl.kt
  app/src/main/java/org/sopt/mcdonalds/data/cart/service/CartService.kt
  app/src/main/java/org/sopt/mcdonalds/domain/cart/model/CartDetail.kt
  app/src/main/java/org/sopt/mcdonalds/domain/cart/repository/CartRepository.kt
  app/src/main/java/org/sopt/mcdonalds/domain/cart/usecase/PostCartUseCase.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/main/MainScreen.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/OrderScreen.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/OrderViewModel.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/component/OrderBurgerDetailContainer.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/navigation/OrderNavigation.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/state/OrderContract.kt
Labels: ✨ Feature, 🤩 형석

#46 [FEAT/#43] 남은 API 연결 및 전반적인 코드 수정
  app/src/main/java/org/sopt/mcdonalds/core/designsystem/component/NumberIncrementer.kt
  app/src/main/java/org/sopt/mcdonalds/data/dummy/datasource/.gitkeep
  app/src/main/java/org/sopt/mcdonalds/data/dummy/di/.gitkeep
  app/src/main/java/org/sopt/mcdonalds/data/dummy/dto/.gitkeep
  app/src/main/java/org/sopt/mcdonalds/data/dummy/mapper/.gitkeep
  app/src/main/java/org/sopt/mcdonalds/data/dummy/repository/.gitkeep
  app/src/main/java/org/sopt/mcdonalds/data/dummy/service/.gitkeep
  app/src/main/java/org/sopt/mcdonalds/data/order/datasource/OrderDataSource.kt
  app/src/main/java/org/sopt/mcdonalds/data/order/di/RepositoryModule.kt
  app/src/main/java/org/sopt/mcdonalds/data/order/di/ServiceModule.kt
  app/src/main/java/org/sopt/mcdonalds/data/order/dto/RecentOrderResponse.kt
  app/src/main/java/org/sopt/mcdonalds/data/order/mapper/OrderMapper.kt
  app/src/main/java/org/sopt/mcdonalds/data/order/repository/OrderRepositoryImpl.kt
  app/src/main/java/org/sopt/mcdonalds/data/order/service/OrderService.kt
  app/src/main/java/org/sopt/mcdonalds/domain/dummy/model/.gitkeep
  app/src/main/java/org/sopt/mcdonalds/domain/dummy/repository/.gitkeep
  app/src/main/java/org/sopt/mcdonalds/domain/dummy/usecase/.gitkeep
  app/src/main/java/org/sopt/mcdonalds/domain/order/repository/OrderRepository.kt
  app/src/main/java/org/sopt/mcdonalds/domain/order/usecase/GetRecentOrderUseCase.kt
  app/src/main/java/org/sopt/mcdonalds/domain/order/usecase/PostOrderUseCase.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/history/HistoryScreen.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/history/HistoryViewModel.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/history/component/CartEditBottomSheetScreen.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/history/model/RecentBurger.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/history/state/HistoryContract.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/main/MainScreen.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/OrderScreen.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/OrderViewModel.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/component/OrderBurgerDetailContainer.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/component/OrderIngredientChangeContainer.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/component/OrderSetSelectButton.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/component/OrderSideChangeContainer.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/component/OrderSideDetailContainer.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/model/Burger.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/state/OrderContract.kt
  app/src/main/java/org/sopt/mcdonalds/presentation/order/type/OrderType.kt
  app/src/main/res/drawable/img_drink_sprite_large.png
  app/src/main/res/values/strings.xml
Labels: ⚙ Setting, 🐛 Fix, 🔨 Refactor, 🌏 Deploy, ✨ Feature, ✅ Test, 📬 API, 💄 Design, 🙋‍♂️ Question, 📃 Docs, 😎 종명, 🤩 형석, 😍 성하
